-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-04-23 10:41:37 SELČ
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AKTIVITA 
    ( 
     id_aktivity INTEGER  NOT NULL , 
     nazev       VARCHAR2 (40)  NOT NULL , 
     popis       VARCHAR2 (50) , 
     cena        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE AKTIVITA 
    ADD CONSTRAINT Aktivita_PK PRIMARY KEY ( id_aktivity ) ;

CREATE TABLE CHATKA 
    ( 
     id_chatky               INTEGER  NOT NULL , 
     cislo_chatky            INTEGER  NOT NULL , 
     kapacita                INTEGER  NOT NULL , 
     cena_za_noc_dospely     INTEGER  NOT NULL , 
     cena_za_noc_dite        INTEGER  NOT NULL , 
     cena_za_noc_dite_do_tri INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CHATKA 
    ADD CONSTRAINT Chatka_PK PRIMARY KEY ( id_chatky ) ;

CREATE TABLE REZERVACE 
    ( 
     id_rezervace          INTEGER  NOT NULL , 
     rezervovano_od        DATE  NOT NULL , 
     rezervovano_do        DATE  NOT NULL , 
     celkova_cena          INTEGER  NOT NULL , 
     stav_rezervace        VARCHAR2 (15)  NOT NULL , 
     datum_vytvoreni       DATE  NOT NULL , 
     Zakaznik_id_zakaznika INTEGER , 
     Chatka_id_chatky      INTEGER 
    ) 
;

ALTER TABLE REZERVACE 
    ADD CONSTRAINT Rezervace_PK PRIMARY KEY ( id_rezervace ) ;

CREATE TABLE REZERVACE_AKTIVITY 
    ( 
     id_rezervace_aktivity  INTEGER  NOT NULL , 
     pocet_hodin            INTEGER  NOT NULL , 
     Rezervace_id_rezervace INTEGER  NOT NULL , 
     AKTIVITA_id_aktivity   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE REZERVACE_AKTIVITY 
    ADD CONSTRAINT Rezervace_aktivity_PK PRIMARY KEY ( id_rezervace_aktivity ) ;

CREATE TABLE STRAVA 
    ( 
     id_strava                INTEGER  NOT NULL , 
     pocet_dni                INTEGER  NOT NULL , 
     Typ_stravy_id_typ_stravy INTEGER  NOT NULL , 
     Ubytovane_Osoby_id_osoba INTEGER  NOT NULL 
    ) 
;

ALTER TABLE STRAVA 
    ADD CONSTRAINT STRAVA_PK PRIMARY KEY ( id_strava ) ;

CREATE TABLE TYP_STRAVY 
    ( 
     id_typ_stravy        INTEGER  NOT NULL , 
     typ                  VARCHAR2 (20)  NOT NULL , 
     cena_den_dospely     INTEGER  NOT NULL , 
     cena_den_dite        INTEGER  NOT NULL , 
     cena_den_dite_do_tri INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TYP_STRAVY 
    ADD CONSTRAINT Typ_stravy_PK PRIMARY KEY ( id_typ_stravy ) ;

CREATE TABLE UBYTOVANA_OSOBA 
    ( 
     id_osoba               INTEGER  NOT NULL , 
     jmeno                  VARCHAR2 (40)  NOT NULL , 
     prijmeni               VARCHAR2 (40)  NOT NULL , 
     rodne_cislo            VARCHAR2 (11)  NOT NULL , 
     datum_narozeni         DATE  NOT NULL , 
     typ_osoby              VARCHAR2 (20)  NOT NULL , 
     Rezervace_id_rezervace INTEGER  NOT NULL 
    ) 
;

ALTER TABLE UBYTOVANA_OSOBA 
    ADD CONSTRAINT Ubytovane_Osoby_PK PRIMARY KEY ( id_osoba ) ;

ALTER TABLE UBYTOVANA_OSOBA 
    ADD CONSTRAINT UBYTOVANA_OSOBA__UN UNIQUE ( rodne_cislo ) ;

CREATE TABLE ZAKAZNIK 
    ( 
     id_zakaznika INTEGER  NOT NULL , 
     jmeno        VARCHAR2 (40)  NOT NULL , 
     prijmeni     VARCHAR2 (40)  NOT NULL , 
     telefon      INTEGER  NOT NULL , 
     email        VARCHAR2 (40)  NOT NULL 
    ) 
;

ALTER TABLE ZAKAZNIK 
    ADD CONSTRAINT Zakaznik_PK PRIMARY KEY ( id_zakaznika ) ;

ALTER TABLE ZAKAZNIK 
    ADD CONSTRAINT ZAKAZNIK__UN UNIQUE ( email ) ;

ALTER TABLE REZERVACE_AKTIVITY 
    ADD CONSTRAINT FK_REZ_AKT_REZ FOREIGN KEY 
    ( 
     Rezervace_id_rezervace
    ) 
    REFERENCES REZERVACE 
    ( 
     id_rezervace
    ) 
;

ALTER TABLE REZERVACE_AKTIVITY 
    ADD CONSTRAINT FK_REZ_AKT_REZERVACE FOREIGN KEY 
    ( 
     AKTIVITA_id_aktivity
    ) 
    REFERENCES AKTIVITA 
    ( 
     id_aktivity
    ) 
;

ALTER TABLE REZERVACE 
    ADD CONSTRAINT Rezervace_Chatka_FK FOREIGN KEY 
    ( 
     Chatka_id_chatky
    ) 
    REFERENCES CHATKA 
    ( 
     id_chatky
    ) 
;

ALTER TABLE REZERVACE 
    ADD CONSTRAINT Rezervace_Zakaznik_FK FOREIGN KEY 
    ( 
     Zakaznik_id_zakaznika
    ) 
    REFERENCES ZAKAZNIK 
    ( 
     id_zakaznika
    ) 
;

ALTER TABLE STRAVA 
    ADD CONSTRAINT Strava_Typ_stravy_FK FOREIGN KEY 
    ( 
     Typ_stravy_id_typ_stravy
    ) 
    REFERENCES TYP_STRAVY 
    ( 
     id_typ_stravy
    ) 
;

ALTER TABLE STRAVA 
    ADD CONSTRAINT Strava_Ubytovane_Osoby_FK FOREIGN KEY 
    ( 
     Ubytovane_Osoby_id_osoba
    ) 
    REFERENCES UBYTOVANA_OSOBA 
    ( 
     id_osoba
    ) 
;

ALTER TABLE UBYTOVANA_OSOBA 
    ADD CONSTRAINT Ubytovane_Osoby_Rezervace_FK FOREIGN KEY 
    ( 
     Rezervace_id_rezervace
    ) 
    REFERENCES REZERVACE 
    ( 
     id_rezervace
    ) 
;

INSERT INTO AKTIVITA VALUES (1, 'Kanoe', 'Půjčení kanoe', 100);
INSERT INTO AKTIVITA VALUES (2, 'Úniková hra', 'Zakoupení brožury', 150);
INSERT INTO AKTIVITA VALUES (3, 'Motorový člun', 'Půjčení motorového člunu', 200);

INSERT INTO CHATKA VALUES (1, 1, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (2, 2, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (3, 3, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (4, 4, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (5, 5, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (6, 6, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (7, 7, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (8, 8, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (9, 9, 5, 900, 900, 0);
INSERT INTO CHATKA VALUES (10, 10, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (11, 11, 4, 900, 900, 0);
INSERT INTO CHATKA VALUES (12, 12, 5, 900, 900, 0);

INSERT INTO TYP_STRAVY VALUES (1, 'Plná penze', 390, 290, 0);
INSERT INTO TYP_STRAVY VALUES (2, 'Bez stravy', 0, 0, 0);


CREATE SEQUENCE zakaznik_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE rezervace_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE osoba_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE rez_akt_seq START WITH 1 INCREMENT BY 1;

SELECT * FROM ZAKAZNIK;
